version: '3'

services:
  pfa-mysql:
    container_name: pfa-mysql
    build: ./mysql
    volumes:
      - ./db:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_PASSWORD_ROOT=root
  pfa-node:
    container_name: pfa-node
    build: ./node
    volumes:
      - ./node:/home/node/app
      - /home/node/app/node_modules
    environment:
      - MYSQL_PASSWORD_ROOT=root
    depends_on:
      - pfa-mysql
  pfa-nginx:
    container_name: pfa-nginx
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - pfa-node
  